/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SYSTEM_AISSYSTEM_PB_H_INCLUDED
#define PB_SYSTEM_AISSYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _System_ConfigSystemData {
    char userSystemID[10];
    char ssidWifiSta[32];
    char passWifiSta[32];
    char uriMqtt[96];
    uint32_t portMqtt;
    char mqttUser[32];
    char mqttPass[32];
} System_ConfigSystemData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define System_ConfigSystemData_init_default     {"", "", "", "", 0, "", ""}
#define System_ConfigSystemData_init_zero        {"", "", "", "", 0, "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define System_ConfigSystemData_userSystemID_tag 1
#define System_ConfigSystemData_ssidWifiSta_tag  2
#define System_ConfigSystemData_passWifiSta_tag  3
#define System_ConfigSystemData_uriMqtt_tag      4
#define System_ConfigSystemData_portMqtt_tag     5
#define System_ConfigSystemData_mqttUser_tag     6
#define System_ConfigSystemData_mqttPass_tag     7

/* Struct field encoding specification for nanopb */
#define System_ConfigSystemData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   userSystemID,      1) \
X(a, STATIC,   REQUIRED, STRING,   ssidWifiSta,       2) \
X(a, STATIC,   REQUIRED, STRING,   passWifiSta,       3) \
X(a, STATIC,   REQUIRED, STRING,   uriMqtt,           4) \
X(a, STATIC,   REQUIRED, UINT32,   portMqtt,          5) \
X(a, STATIC,   REQUIRED, STRING,   mqttUser,          6) \
X(a, STATIC,   REQUIRED, STRING,   mqttPass,          7)
#define System_ConfigSystemData_CALLBACK NULL
#define System_ConfigSystemData_DEFAULT NULL

extern const pb_msgdesc_t System_ConfigSystemData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define System_ConfigSystemData_fields &System_ConfigSystemData_msg

/* Maximum encoded size of messages (where known) */
#define SYSTEM_AISSYSTEM_PB_H_MAX_SIZE           System_ConfigSystemData_size
#define System_ConfigSystemData_size             246

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
