/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AQUACTRL_AQUACONTROL_PB_H_INCLUDED
#define PB_AQUACTRL_AQUACONTROL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AquaCtrl_ControlRelayData {
    uint32_t channel;
    uint32_t status_control;
} AquaCtrl_ControlRelayData;

typedef struct _AquaCtrl_MonitorAquaControlData {
    uint32_t AmpeChannel1x100;
    uint32_t AmpeChannel2x100;
    uint32_t IsPowerLostPhare;
    uint32_t IsLostElectric;
} AquaCtrl_MonitorAquaControlData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AquaCtrl_ControlRelayData_init_default   {0, 0}
#define AquaCtrl_MonitorAquaControlData_init_default {0, 0, 0, 0}
#define AquaCtrl_ControlRelayData_init_zero      {0, 0}
#define AquaCtrl_MonitorAquaControlData_init_zero {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AquaCtrl_ControlRelayData_channel_tag    1
#define AquaCtrl_ControlRelayData_status_control_tag 2
#define AquaCtrl_MonitorAquaControlData_AmpeChannel1x100_tag 1
#define AquaCtrl_MonitorAquaControlData_AmpeChannel2x100_tag 2
#define AquaCtrl_MonitorAquaControlData_IsPowerLostPhare_tag 3
#define AquaCtrl_MonitorAquaControlData_IsLostElectric_tag 4

/* Struct field encoding specification for nanopb */
#define AquaCtrl_ControlRelayData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   channel,           1) \
X(a, STATIC,   REQUIRED, UINT32,   status_control,    2)
#define AquaCtrl_ControlRelayData_CALLBACK NULL
#define AquaCtrl_ControlRelayData_DEFAULT NULL

#define AquaCtrl_MonitorAquaControlData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   AmpeChannel1x100,   1) \
X(a, STATIC,   REQUIRED, UINT32,   AmpeChannel2x100,   2) \
X(a, STATIC,   REQUIRED, UINT32,   IsPowerLostPhare,   3) \
X(a, STATIC,   REQUIRED, UINT32,   IsLostElectric,    4)
#define AquaCtrl_MonitorAquaControlData_CALLBACK NULL
#define AquaCtrl_MonitorAquaControlData_DEFAULT NULL

extern const pb_msgdesc_t AquaCtrl_ControlRelayData_msg;
extern const pb_msgdesc_t AquaCtrl_MonitorAquaControlData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AquaCtrl_ControlRelayData_fields &AquaCtrl_ControlRelayData_msg
#define AquaCtrl_MonitorAquaControlData_fields &AquaCtrl_MonitorAquaControlData_msg

/* Maximum encoded size of messages (where known) */
#define AQUACTRL_AQUACONTROL_PB_H_MAX_SIZE       AquaCtrl_MonitorAquaControlData_size
#define AquaCtrl_ControlRelayData_size           12
#define AquaCtrl_MonitorAquaControlData_size     24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
